### ISSUE TITLE
completion for npm is super slow

### ISSUE THREAD

**Issue by ovikholt** [hchbaw/auto-fu.zsh#33] opened 2014-08-21 10:13 UTC
Type 'npm' then space and another character. Another of these lines is printed every second

```
$ npm egrep: empty (sub)expression
egrep: empty (sub)expression
egrep: empty (sub)expression
egrep: empty (sub)expression
egrep: empty (sub)expression
egrep: empty (sub)expression
...
```

**Comment by hchbaw** [comment] 2014-08-23 01:10
Hi, @ovikholt !  Thank you very much for your feedback.

Unfortunately, I cannot reproduce.  Dose `npm`'s completion work correctly without `auto-fu.zsh`?

**Comment by chenglou** [comment] 2015-01-19 07:23
@ovikholt here's the answer: http://segmentfault.com/q/1010000000743734/a-1020000000743738
Which links to this: https://docs.npmjs.com/cli/completion

This solves the problem for me. Unfortunately, npm completion itself is super slow (https://github.com/npm/npm/issues/6671). In the meantime I've disabled it by commenting [this](https://github.com/npm/npm/blob/41ecebe3009cb9b53b46b871c00f1133e3eb92cf/lib/utils/completion.sh#L28-L33) out.

@hchbaw I think you can close this. This isn't auto-fu's fault.

**Comment by hchbaw** [comment] 2015-01-20 13:31
@chenglou thank you very much for your efforts.

**Closed as completed by hchbaw** 2015-01-20 13:31 UTC
